# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c89bd72f5cf64c553923dc98bd2f1dbbcbe10ea52a244831478eef73284350f4f4b270581a98a2a3647d4327867eff958af6a8ccb5638592f27c158982bc328

test:
  secret_key_base: 74b369a76cdc7f20a16ba216c8ed644bd4e1a06dec914d6888d246c6e9268ec857ed0ce912931cf5b2f0181f4470193f4370ee86c398332d71046c91e9a3fba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
